{% set name = "telnyx" %}
{% set version = "1.3.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/telnyx-{{ version }}.tar.gz
  sha256: 354429ced1d2521c08f020091f336a9b04e9694a75b66c8feabbcd7e8d4474f7

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest
    - python >=3.6
  run:
    - pynacl
    - python >=3.6
    - requests >=2.20

test:
  imports:
    - telnyx
    - telnyx.api_resources
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/team-telnyx/telnyx-python
  summary: Python bindings for the Telnyx API
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kcemenike
